apiVersion: v1
kind: Service
metadata:
  name: digifab-quoting-admin
  namespace: digifab-quoting
spec:
  type: ClusterIP
  selector:
    app: digifab-quoting-admin
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
