apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digifab-quoting
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- worker-deployment.yaml
- network-policies.yaml
images:
- digest: sha256:e3b36b43cb62b33674dd9ec6009384dfa5e026dd8fbb913110652e15b47b8115
  name: ghcr.io/madfam-org/digifab-quoting/api
  newName: ghcr.io/madfam-org/digifab-quoting/api
- digest: sha256:2a2bcf2f6ca02c0b00b4982caa5313384c267696bc4fbbd7debdaa7e90db391c
  name: ghcr.io/madfam-org/digifab-quoting/web
  newName: ghcr.io/madfam-org/digifab-quoting/web
- digest: sha256:ad5ecee9d9b6b95505cfadd421bf11e9cea8698d3a14ca2b8149a0dec07da3d9
  name: ghcr.io/madfam-org/digifab-quoting/worker
  newName: ghcr.io/madfam-org/digifab-quoting/worker
