apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digifab-quoting
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- worker-deployment.yaml
- network-policies.yaml
images:
- digest: sha256:0d53071819a587271981cbf684bdfd91309318f8f17a13b89e68e3c36895712f
  name: ghcr.io/madfam-org/digifab-quoting/api
  newName: ghcr.io/madfam-org/digifab-quoting/api
- digest: sha256:5ccaf6a62b3933c376bd8387706525436628761a33571f73e0289c00543e9f30
  name: ghcr.io/madfam-org/digifab-quoting/web
  newName: ghcr.io/madfam-org/digifab-quoting/web
- digest: sha256:625ac3aa9f43b5c547874fdf0c8afa643e530e755aab449889796ac1116d1892
  name: ghcr.io/madfam-org/digifab-quoting/worker
  newName: ghcr.io/madfam-org/digifab-quoting/worker
