apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digifab-quoting
resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- worker-deployment.yaml
- network-policies.yaml
images:
- digest: sha256:bd06831d302bb149c3f8a3d7c6f545d261ec3f29a63edd223f364a22dd3a89bf
  name: ghcr.io/madfam-org/digifab-quoting/api
  newName: ghcr.io/madfam-org/digifab-quoting/api
- digest: sha256:683a731f17ddc99b1e7fcf784bb233b04ec80986548821cbcbc41891fc875922
  name: ghcr.io/madfam-org/digifab-quoting/web
  newName: ghcr.io/madfam-org/digifab-quoting/web
- digest: sha256:0d3825fe43d756a2d0e3c7827126e41349c1a2b47523f446c419b1be51c4e84e
  name: ghcr.io/madfam-org/digifab-quoting/worker
  newName: ghcr.io/madfam-org/digifab-quoting/worker
